# 手写实现版本

In [2]:
import torch
X = torch.tensor([
    [1,1,1],
    [1,0,1],
    [1,0,0],
    [1,1,0],
],dtype=torch.float32)
y = torch.tensor([0.2,0.3,-0.3,0.15])

W = torch.randn(3,1)

yhat = torch.mm(X,W)

print(X)
print(W)
print(yhat)


tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 0.],
        [1., 1., 0.]])
tensor([[-0.3639],
        [ 0.4787],
        [-1.6978]])
tensor([[-1.5830],
        [-2.0617],
        [-0.3639],
        [ 0.1148]])


# pytorch api实现版本

In [3]:
import torch.nn as nn
X = torch.tensor([
    [1,1,1],
    [1,0,1],
    [1,0,0],
    [1,1,0],
],dtype=torch.float32)
y = torch.tensor([0.2,0.3,-0.3,0.15])

liner_layer = nn.Linear(in_features=3, out_features=1, bias=False)

yhat = liner_layer(X)
yhat

tensor([[ 0.1098],
        [-0.2954],
        [-0.3312],
        [ 0.0741]], grad_fn=<MmBackward0>)