# 手写实现版本

In [6]:
import torch
X = torch.tensor([
    [1,1,1],
    [1,0,1],
    [1,0,0],
    [1,1,0],
],dtype=torch.float32)
y = torch.tensor([0.2,0.3,-0.3,0.15])

W = torch.randn(3,1)

yhat = torch.mm(X,W)

print(X)
print(W)
print(yhat)


tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 0.],
        [1., 1., 0.]])
tensor([[ 0.2461],
        [-1.1338],
        [-1.3815]])
tensor([[-2.2692],
        [-1.1353],
        [ 0.2461],
        [-0.8877]])


# pytorch api实现版本

In [7]:
import torch.nn as nn
X = torch.tensor([
    [1,1,1],
    [1,0,1],
    [1,0,0],
    [1,1,0],
],dtype=torch.float32)
y = torch.tensor([0.2,0.3,-0.3,0.15])

liner_layer = nn.Linear(in_features=3, out_features=1, bias=False)

yhat = liner_layer(X)
yhat

tensor([[ 0.1466],
        [-0.1590],
        [ 0.1397],
        [ 0.4453]], grad_fn=<MmBackward0>)

# 损失函数

## 回归损失（MSE）loss